#
#
# This file is part of the Shotgun Pipeline Toolkit default configuration. It shows how to
# do shot specific overrides of constants, values etc.
# 
# By defining values or collections of values in this file, and then making sure it is 
# included in the master configuration, any values defined here which are used in the master
# configuration will be overridden.
#
#

# example of how to override the verson of maya used in this context.
#
# maya_windows: 'C:\Program Files\Autodesk\maya2015\bin\maya.exe'
# maya_mac: /Applications/Autodesk/maya2015/Maya.app
# maya_linux: maya_alt
