# Shotgun Pipeline Toolkit configuration file
# This file was automatically created by setup_project
# This file reflects the paths in the primary pipeline
# configuration defined for this project.

Windows: 'T:/software\genericconfig'
Darwin: '/volumes/genericconfig'
Linux: '/development/genericconfig'

# End of file.
